socialmedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("web/",include('web.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("register/",SignUpView.as_view(),name="signup"),
    path("login/",SignInView.as_view(),name="signin"),
    path("index/",IndexView.as_view(),name="index"),
    path("posts/<int:id>/comment/add/",add_comments,name="add-comments"),
    path("post/<int:id>/like/add/",like_posts,name="add-like"),
    path("logout/",signout_view,name="logout"),
    path("add_post/",AddPost.as_view(),name="add-post"),
    path("profile/",ProfileView.as_view(),name="profile"),
    path("post/<int:id>/remove/",profile_delete_view,name="post-delete"),
    path("index/comment/<int:id>/remove",comment_delete_view,name="comment-del"),
    path("post/update/",edit_profile,name="edit-profile"),
    path("people/", ListPeopleView.as_view(), name="people"),
    path("user/<int:id>/follower/add", add_follower, name="add-follower"),
    path("profile/add/",AddProfileView.as_view(),name="profilepic"),
    path("profile/<int:id>/edit/",EditprofileView.as_view(),name="edit-pic"),
    path("frinds/",FollowingView.as_view(),name="following")


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count


# Create your models here.
class Posts(models.Model):
    title=models.CharField(max_length=250)
    image=models.ImageField(upload_to="images",null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_date=models.DateField(auto_now_add=True)
    like=models.ManyToManyField(User,related_name="likes")

    @property
    def likes(self):
        qs=self.like.all().count()
        return qs

    @property
    def posts_comments(self):
        return self.comments_set.all()

    

    def _str_(self):
        return self.title

class Comments(models.Model):
    comment=models.CharField(max_length=250)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    post=models.ForeignKey(Posts,on_delete=models.CASCADE)
    created_date=models.DateField(auto_now_add=True)

    def _str_(self):
        return self.comment

class Userprofile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    profile_pic=models.ImageField(upload_to="profile_pics",null=True)
    timelinepic=models.ImageField(upload_to="timelinepic",null=True)


class Friends(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    date = models.DateTimeField(auto_now_add=True)

web/templates/post/post_create.html
<div class="card border-0 shadow-sm ms-5" >
    <div class="card-body">
        <div class="input-group" style="width: 100%; height: 3em;">

            <span class="input-group-text border-0 " data-bs-toggle="modal" data-bs-target="#exampleModal"
                id="basic-addon1">@</span>
            <input type="text" class="form-control border-0" placeholder="Share whats on your mind, {{request.user}}. ." aria-label="Username"
                aria-describedby="basic-addon1" data-bs-toggle="modal" data-bs-target="#exampleModal">
        </div>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input class="btn btn-outline-info form-control btn-sm" type="submit" name="" id="" value="Add">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>



{% comment %} <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="post" class="btn btn-primary">
</form> {% endcomment %}

web/templates/post/post_list.html
{% for post in posts %}

<div class="card-div mt-4 mb-2 ms-5">
    <div class="card p-2 border border-0 shadow-sm" style="width: 100%">
        <img src="{{post.image.url}}" width="100%" alt="">
        <div class="card-body">
            <p class="card-text">{{post.title}}</p>

            <div class="btn-group border border-0" style="width: 100%;;" role="group" aria-label="Basic example">
                <a type="button" class="btn btn-outline-light shadow-sm text-dark">Repost</a>
                <button type="button" class="btn btn-outline-light shadow-sm text-dark collapsed"
                    data-bs-toggle="collapse" data-bs-target="#flush-collapse{{post.id}}" aria-expanded="false"
                    aria-controls="flush-collapseOne">Comment</button>
                    {%if request.user in post.like.all %}
                    <a href="{%url 'add-like' post.id%}" style="height: 30px;color: grey;"><i class="fa-solid fa-heart" style="height: 30px;color: red;outline: none;"></i>{{post.likes}}</a>
                    {%else%}
                    <a href="{%url 'add-like' post.id%}" style="height: 30px;color: grey;"><i class="fa-regular fa-heart" style="height: 30px;color: red;outline: none;"></i>{{post.likes}}</a>
                    {%endif%} 

            </div>

            <!-- comment section -->
            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                    <div id="flush-collapse{{post.id}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                        data-bs-parent="#accordionFlushExample" style="">

                        <form action="{% url 'add-comments' post.id %}" method="post">
                            {% csrf_token %}
                            <textarea name="comment" class="form-control" id="id_comment" cols="74" rows="5"></textarea>
                            <input type="submit" value="submit" class="btn btn-outline-primary">
                        </form>

                        {% for comment in post.comments %}
                        <div class="accordion-body bg-light m-1 mt-2">
                            <div class="">
                                <p><small>@{{comment.user}}</small></p>
                                <p>{{comment.comment}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- end of comment section -->

            

            
        </div>
    </div>
</div>

{% endfor %}

web/templates/post/trending-posts.html
<style>
    .main{
    }
</style>

<div class="card p-3 mt-3 border-0 shadow-sm" style="width: 90%;" >
    <div class="card-body">
        <div class="row main ">
            {% for t in posts %}
            <div class="card mb-3 border-0 child" style="max-width: 100%;">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src="{{t.image.url}}" width="100%" class="img-fluid rounded-start" alt="...">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h6 style="margin: 0;margin-top: -20px;" class="card-title">{{t.title}}</h6>
                      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>
                  </div>
                </div>
            </div>
            {% endfor %}
        </div>  
    </div>
</div>